const CONTENT_SECURITY_POLICY_DIRECTIVES = [
  "default-src 'self'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: https://www.googletagmanager.com https://static.cloudflareinsights.com https://analytics.ahrefs.com",
  "frame-src 'self' https://www.googletagmanager.com https://www.youtube.com https://www.youtube-nocookie.com https://clipy.online",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data: https:",
  "connect-src 'self' https: http: ws: wss:",
  "media-src 'self' blob: https:",
];

export const CONTENT_SECURITY_POLICY = [...CONTENT_SECURITY_POLICY_DIRECTIVES, 'upgrade-insecure-requests'].join('; ');

export const LOCAL_CONTENT_SECURITY_POLICY = CONTENT_SECURITY_POLICY_DIRECTIVES.join('; ');

export const LOCAL_HOST_PATTERN = 'localhost|127\\.0\\.0\\.1';

export const SECURITY_HEADERS = [
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'Permissions-Policy', value: 'geolocation=(), microphone=(), camera=(), payment=(), usb=()' },
  { key: 'Strict-Transport-Security', value: 'max-age=31536000; includeSubDomains' },
];

export function renderStaticHeaders({ production }: { production: boolean }): string {
  const headers = [
    ...SECURITY_HEADERS,
    { key: 'Content-Security-Policy', value: CONTENT_SECURITY_POLICY },
    ...(production ? [] : [{ key: 'X-Robots-Tag', value: 'noindex, nofollow' }]),
  ];
  return [
    '# Generated by scripts/generate-static-headers.ts from src/lib/http/securityHeaders.ts for a',
    `# ${production ? 'production' : 'non-production'} build (SITE_ENV). Do not edit or commit it.`,
    '/*',
    ...headers.map(({ key, value }) => `  ${key}: ${value}`),
    '',
  ].join('\n');
}
