import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const templates = sqliteTable("templates", {
  id: text("id").primaryKey(),
  user_id: text("user_id").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  items: text("items").notNull(),
  version: integer("version").notNull().default(1),
  type: text("type").notNull().default("checklist"),
  seo_title: text("seo_title"),
  seo_description: text("seo_description"),
  rules: text("rules"),
  owner_type: text("owner_type").notNull().default("user"),
  team_id: text("team_id"),
  created_by_user_id: text("created_by_user_id"),
  updated_by_user_id: text("updated_by_user_id"),
  is_public: integer("is_public", { mode: "boolean" }).default(false),
  category: text("category"),
  tags: text("tags"),
  slug: text("slug"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at"),
  deleted_at: text("deleted_at"),
});
