import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { is, SQL } from "drizzle-orm";
import { getTableConfig, SQLiteTable } from "drizzle-orm/sqlite-core";
import * as schema from "../db/schema/index";
import { matchesGeneratedText } from "./lib/line-endings.mjs";

const outputPath = path.join(process.cwd(), "docs/generated/db-schema.md");
const sqlOnlyPath = path.join(process.cwd(), "db/sql-only-schema.json");

const escapeCell = (value: string) => value.replace(/\|/g, "\\|").replace(/\n/g, " ");

function formatDefault(value: unknown): string {
  if (value === undefined) return "";
  if (is(value, SQL)) {
    return value.queryChunks
      .map((chunk) => (typeof chunk === "object" && chunk !== null && "value" in chunk ? String(chunk.value) : String(chunk)))
      .join("")
      .trim();
  }
  return JSON.stringify(value);
}

const exported: unknown[] = Object.values(schema);
const tables = exported
  .filter((value): value is SQLiteTable => is(value, SQLiteTable))
  .map((table) => getTableConfig(table))
  .sort((a, b) => a.name.localeCompare(b.name));

const lines: string[] = [
  "# Database Schema",
  "",
  "<!-- Generated by `pnpm run db:schema:generate` from db/schema/. Do not edit by hand. -->",
  "",
  "D1 (SQLite) tables as defined in the Drizzle schema. Ownership, migrations, and",
  "environments are described in [database operations](../design-docs/database-operations.md).",
  "Tables named `team*` and `team_id` columns are legacy names for Organizations.",
  "",
  `Tables: ${tables.map((table) => `[\`${table.name}\`](#${table.name})`).join(", ")}`,
];

for (const table of tables) {
  const primaryKeyColumns = new Set(table.primaryKeys.flatMap((key) => key.columns.map((column) => column.name)));
  lines.push("", `## ${table.name}`, "", "| Column | Type | Null | Default | Key |", "| --- | --- | --- | --- | --- |");
  for (const column of table.columns) {
    const foreignKey = table.foreignKeys.find((key) => key.reference().columns.some((ref) => ref.name === column.name));
    const reference = foreignKey
      ? (() => {
          const ref = foreignKey.reference();
          const target = getTableConfig(ref.foreignTable);
          const onDelete = foreignKey.onDelete ? ` (on delete ${foreignKey.onDelete})` : "";
          return `FK → ${target.name}.${ref.foreignColumns.map((c) => c.name).join(", ")}${onDelete}`;
        })()
      : "";
    const key = [column.primary || primaryKeyColumns.has(column.name) ? "PK" : "", column.isUnique ? "unique" : "", reference]
      .filter(Boolean)
      .join("; ");
    lines.push(
      `| \`${column.name}\` | ${column.getSQLType()} | ${column.notNull ? "no" : "yes"} | ${escapeCell(formatDefault(column.default))} | ${escapeCell(key)} |`,
    );
  }
  if (table.indexes.length > 0) {
    lines.push("", "Indexes:", "");
    for (const index of [...table.indexes].sort((a, b) => a.config.name.localeCompare(b.config.name))) {
      const columns = index.config.columns.map((column) => ("name" in column ? column.name : "(expression)")).join(", ");
      const where = index.config.where ? " (partial)" : "";
      lines.push(`- \`${index.config.name}\`${index.config.unique ? " unique" : ""} on (${columns})${where}`);
    }
  }
}

const sqlOnly = JSON.parse(await readFile(sqlOnlyPath, "utf8")) as { triggers?: { name: string; table: string }[] };
if (sqlOnly.triggers?.length) {
  lines.push("", "## SQL-only triggers", "", "Defined in migrations and recorded in `db/sql-only-schema.json` (Drizzle cannot represent them):", "");
  for (const trigger of [...sqlOnly.triggers].sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`- \`${trigger.name}\` on \`${trigger.table}\``);
  }
}

const output = `${lines.join("\n")}\n`;
if (process.argv.includes("--check")) {
  const existing = await readFile(outputPath, "utf8").catch(() => null);
  if (!matchesGeneratedText(existing, output)) {
    throw new Error("docs/generated/db-schema.md is stale. Run `pnpm run db:schema:generate` and commit it.");
  }
  console.log("docs/generated/db-schema.md is up to date");
} else {
  await writeFile(outputPath, output, "utf8");
  console.log(`Wrote docs/generated/db-schema.md (${tables.length} tables)`);
}
